[package]
name = "notsureyet"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.2"
async_zmq = "0.4.0"
miette = "7.6.0"
zmq = "0.10.0"

[[bin]]
name = "client" 
path = "client/src/main.rs"
[[bin]]
name = "server" 
path = "server/src/main.rs"
